format = """
[](color_user)\
$os\
$username\
[](bg:color_directory fg:color_user)\
$directory\
[](fg:color_directory bg:color_git)\
$git_branch\
$git_status\
[](fg:color_git bg:color_language)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$ocaml\
$python\
$rust\
$scala\
$zig\
[](fg:color_language bg:color_time)\
$time\
[ ](fg:color_time)\
$line_break$character
"""

palette = 'teds_palette'

[palettes.teds_palette]
color_green = '#11ff99'
color_user = '#118855'
color_directory = '#DD5566'
color_git = '#dd7755'
color_language = '#6699bb'
color_time = '#336688'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_user"
style_root = "bg:color_user"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:color_user"
disabled = false # Disabled by default

[os.symbols]
Arch = "󰣇 "
NixOS = " "

[directory]
style = "bg:color_directory"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[character]
disabled = false
success_symbol = '[\$](bold fg:color_user)'
error_symbol = '[\$](bold fg:color_directory)'
vimcmd_symbol = '[\$](bold fg:color_green)'
vimcmd_replace_one_symbol = '[\$](bold fg:color_time)'
vimcmd_replace_symbol = '[\$](bold fg:color_time)'
vimcmd_visual_symbol = '[\$](bold fg:color_git)'

[c]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:color_git"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_git"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_time"
format = '[  $time ]($style)'

[zig]
symbol = " "
style = "bg:color_language"
format = '[ $symbol ($version) ]($style)'
